// flow-typed signature: 7ddc48858cc858bdd2e3df86126c3e50
// flow-typed version: <<STUB>>/eslint-config-rackt_v^1.1.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-rackt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-rackt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-rackt/index' {
  declare module.exports: $Exports<'eslint-config-rackt'>;
}
declare module 'eslint-config-rackt/index.js' {
  declare module.exports: $Exports<'eslint-config-rackt'>;
}
