// flow-typed signature: 1d33683ae9677ed8b619dfd5acb90fcd
// flow-typed version: <<STUB>>/express-urlrewrite_v^1.2.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-urlrewrite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-urlrewrite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'express-urlrewrite/index' {
  declare module.exports: $Exports<'express-urlrewrite'>;
}
declare module 'express-urlrewrite/index.js' {
  declare module.exports: $Exports<'express-urlrewrite'>;
}
