// flow-typed signature: 39eaa99d895bb287fe0d44e6ba95070f
// flow-typed version: <<STUB>>/pretty-bytes_v^3.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-bytes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-bytes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pretty-bytes/index' {
  declare module.exports: $Exports<'pretty-bytes'>;
}
declare module 'pretty-bytes/index.js' {
  declare module.exports: $Exports<'pretty-bytes'>;
}
